apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-go-operator-sdk-import-github-edp-vers.fullname" . }}
  labels:
    {{- include "go-go-operator-sdk-import-github-edp-vers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "go-go-operator-sdk-import-github-edp-vers.selectorLabels" . | nindent 4 }}
